### ISSUE TITLE
no feedback when loading boundary from Overpass

### ISSUE THREAD

**Issue by seb-1204** [hauke96/simple-task-manager#93] opened 2020-08-01 12:12 UTC
Great project, did already several task today.

I tried to use the [overpass turbo query](https://overpass-api.de/api/interpreter?data=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Cname%3D%22Elanora%20Heights%22%20in%20%22Australia%2C%20NSW%22%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20fetch%20area%20%E2%80%9CAustralia%2C%20NSW%E2%80%9D%20to%20search%20in%0Aarea%283602316593%29-%3E.searchArea%3B%0A%2F%2F%20gather%20results%0A%28%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Cname%3D%22Elanora%20Heights%22%E2%80%9D%0A%20%20node%5B%22name%22%3D%22Elanora%20Heights%22%5D%28area.searchArea%29%3B%0A%20%20way%5B%22name%22%3D%22Elanora%20Heights%22%5D%28area.searchArea%29%3B%0A%20%20relation%5B%22name%22%3D%22Elanora%20Heights%22%5D%28area.searchArea%29%3B%0A%29%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B) to define the shape when creating the project. But it would not load or I could not tell if it was still loading/processing or if there was an issue.

**Comment by hauke96** [comment] 2020-08-01 13:07
Thanks for the issue and the example query :) I see three problems here:

1. The query mus result XML but your `out` parameter is set to `json`, so you need `[out:xml]` as output parameter. I'll create a ticket to also support JSON and other formats for remote data.
2. There's no polygon in the result, just a relation with several ways. Unfortunately the import process is rather simple right now, so this is not recognized as one polygon. But I'll create a new ticket for this, maybe that's not so difficult to implement.
3. The missing feedback is an actual bug, because there *is* an error caused by the missing polygon in the result. I'll look into that.

**Comment by seb-1204** [comment] 2020-08-02 00:47
Wow, quick feedback. I did not expect this to be that big of an issue. 
Thinking about this I would rather have the manually drawn polygon workflow improved. See suggestion at [97](https://github.com/hauke96/simple-task-manager/issues/97)

**Comment by hauke96** [comment] 2020-08-30 14:34
Done, this will be fixed in the upcoming 1.1.0 release.

**Closed by hauke96** 2020-08-30 14:34 UTC
Labels: bug
